### PR TITLE
Update HelpMessageComponent.tsx

### PR DESCRIPTION
**Pull request by LLBlue**
now people know what this does

### CODE REVIEW

**Comment by NickGeek** [comment]
Probably would be better if it was in JSDoc style, like:
```
/**
* message
*/
```

**Comment by LLBlue** [comment]
Oh good point that way it would be more readable

**Comment by NickGeek** [comment]
Cool, change looks good. Will merge in :smile:

**Comment by LLBlue** [comment]
Was a pleasure adding my substantive expertise to your small project

**Pull request merged**
